# Generated by Django 6.1 on 2026-09-15
# Fixes: CharField 'contents'/'author' were missing max_length (invalid on CharField).
# 'contents' is switched to TextField since post bodies aren't length-bounded;
# 'author' keeps CharField with a max_length of 100.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
