# Generated by Django 6.1 on 2026-09-15
# - removes the redundant 'index' field (the default auto 'id' primary key
#   already serves as each post's unique, auto-incrementing number)
# - renames 'label' -> 'name' and 'contents' -> 'content' to match the
#   current model field names
# - adds 'created_at' (auto-set on creation) so posts can be ordered

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_post_author_alter_post_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='index',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
