# Generated by Django 6.1 on 2026-09-15
#
# Switches Post.author from a free-typed CharField to a ForeignKey pointing
# at the logged-in user who created the post. The old free-text author
# names aren't valid user references, so existing posts are cleared first
# (per request -- this project has no real post data to preserve yet).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_existing_posts(apps, schema_editor):
    Post = apps.get_model("homepage", "Post")
    Post.objects.all().delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_post_created_at_and_rename_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_existing_posts, noop),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
