"""
Django settings for Forum project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t3&w8=e544m604g0)ag6tz7fxn45=o!9nqv&m^#l%ty)a+$h__'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'homepage',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Lazily deletes accounts that never confirmed their email in time.
    'accounts.middleware.CleanupExpiredRegistrationsMiddleware',
]

ROOT_URLCONF = 'Forum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Forum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Authentication
# https://docs.djangoproject.com/en/6.1/topics/auth/default/

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'homepage'

# How long a newly registered account has to confirm its email before the
# account is deleted automatically (see accounts/middleware.py).
EMAIL_VERIFICATION_TIMEOUT_MINUTES = 30

# Toggle for the email-confirmation step on registration. Set this to True
# to restore the original flow (new accounts start inactive, get a 6-digit
# code emailed to them, and must enter it at accounts:verify before they
# can log in). All of that code (models.EmailVerification, the verify_email
# view, the verify.html template, the accounts:verify URL, and the cleanup
# middleware) is left fully in place below -- flipping this back to True is
# the only step needed to bring it back.
EMAIL_VERIFICATION_ENABLED = False


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Sends confirmation codes through Gmail's SMTP server.
#
# 1. Turn on 2-Step Verification on the Gmail account you want to send from:
#    https://myaccount.google.com/security
# 2. Create an "App Password" for this project:
#    https://myaccount.google.com/apppasswords
#    (this is a 16-character password Google generates for apps -- it is
#    NOT your normal Gmail password, and it's the only thing that should
#    ever go in EMAIL_HOST_PASSWORD below)
# 3. Fill in EMAIL_HOST_USER and EMAIL_HOST_PASSWORD below with your Gmail
#    address and that app password. Don't commit real credentials to a
#    public repo -- keep this file private, or move these two values to
#    environment variables later if you want extra safety.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'rkappassistant@gmail.com'  # <-- fill in your Gmail address
EMAIL_HOST_PASSWORD = 'zyopluxjgduobmap'  # <-- fill in your 16-character Gmail App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
